{
	"threads": 1,
	"batch_size": 5000,
	"sample_only": [
		"mozilla-aurora",
		"try"
	],
	"elasticsearch": {
		"host": "http://54.149.35.214",
		"port": 9200,
		"index": "unittest",
		"type": "test_result",
		"timeout": 300,
		"schema": {
			"$ref": "//../../schema/test_results.json"
		},
		"debug": true,
		"limit_replicas": false
	},
	"source": {
		"$ref": "file://~/private.json#aws_credentials",
		"bucket": "ekyle-test-result",
		"key_format": "a:b.c"
	},
	"work_queue":{
		"name": "active-data-index",
		"debug": true,
		"$ref": "file://~/private.json#aws_credentials"
	},
	"constants": {
		"pyLibrary.env.http.default_headers": {
			"Referer": "https://wiki.mozilla.org/Auto-tools/Projects/ActiveData",
			"User-Agent": "testlog-etl"
		}
	},
	"debug": {
		"trace":true,
		"log": [
			{
				"log_type": "console"
			},
			{
				"log_type": "email",
				"from_address": "klahnakoski@mozilla.com",
				"to_address": "klahnakoski@mozilla.com",
				"subject": "[ALERT][DEV]Problem in Push unit to ES",
				"$ref": "file://~/private.json#email"

			}
		]
	}
}
