{
	"processes": 1,
	"sample_only": [
		"b2g-inbound",
		"fx-team",
		"mozilla-aurora",
		"try"
	],
	"elasticsearch": {
		"use_daily": true,
		"host": "http://54.149.35.214",
		"port": 9200,
		"index": "unittest",
		"type": "test_result",
		"timeout": 300,
		"schema": {
			"$ref": "//../schema/test_results.json"
		},
		"debug": false,
		"limit_replicas": false
	},
	"source": {
		"$ref": "file://~/private.json#aws_credentials",
		"bucket": "ekyle-test-result",
		"key_format": "a:b.c"
	},
	"work_queue":{
		"name": "ekyle-etl",
		"debug": true,
		"$ref": "file://~/private.json#aws_credentials"
	},
	"constants": {
		"pyLibrary.env.http.default_headers": {
			"From": "https://wiki.mozilla.org/Auto-tools/Projects/ActiveData"
		}
	},
	"debug": {
		"cprofile": {
			"enabled": true,
			"filename": "./results/cprofile.tab"
		},
		"log": [
			{
				"log_type": "console"
			},
			{
				"log_type": "email",
				"from_address": "klahnakoski@mozilla.com",
				"to_address": "klahnakoski@mozilla.com",
				"subject": "[ALERT][DEV]Problem in Push to ES",
				"$ref": "file://~/private.json#email"

			}
		]
	}
}
